#!/bin/bash

set -e

extract() {
	ASAHIFW="/boot/efi/asahi"
	VENDORFW="/run/.system-efi/vendorfw"
	VENDORFWTMP="/run/.vendorfw-tmp"

	if [ ! -e "${ASAHIFW}/all_firmware.tar.gz" ]; then
		printf "==> No ${ASAHIFW}/all_firmware.tar.gz, skipping firmware extraction"
	fi
	printf '==> Upgrading vendor firmware package...\n'

	asahi-fwextract "$ASAHIFW" "$VENDORFWTMP"
	rm -rf "$VENDORFW".new
	mv "${VENDORFWTMP}" "$VENDORFW".new
	rm -rf "$VENDORFW"
	mv "$VENDORFW".new "$VENDORFW"
	rm -rf "$VENDORFWTMP"

	printf '    Firmware upgraded\n'
}

case "$1" in
	configure)
		extract
	;;
	abort-upgrade|abort-remove|abort-deconfigure)
	;;
	*)
		echo "postinst called with unknown argument \`$1'" >&2
		exit 0
	;;
esac

#DEBHELPER#

