#!/bin/bash

set -e

extract() {
	if [ ! -e /boot/efi/asahi/all_firmware.tar.gz ]; then
		printf '==> No /boot/efi/asahi/all_firmware.tar.gz, skipping firmware extraction'
	fi
	printf '==> Upgrading vendor firmware package...\n'
	mkdir -p /run/.vendorfw-tmp
	python3 -m asahi_firmware.update /boot/efi/asahi /run/.vendorfw-tmp
	mv -f /run/.vendorfw-tmp/* /boot/efi/vendorfw/
	printf '    Firmware upgraded\n'
	update-vendor-firmware
}

case "$1" in
	configure)
		extract
	;;
	abort-upgrade|abort-remove|abort-deconfigure)
	;;
	*)
		echo "postinst called with unknown argument \`$1'" >&2
		exit 0
	;;
esac

#DEBHELPER#

